apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  volumes:
    - name: sharedvolume
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: vol
      hostPath:
        path: /usr/local/bin/helm
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
  containers:
  - name: helm
    image: "alpine/helm:2.14.0"
    ttyEnabled: true
    volumeMounts:
    - name: vol
      mountPath: /usr/local/bin/helm
    command:
    - sleep
    args:
    - "9999999"
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "1000Mi"
        cpu: "500m"
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - sleep
    args:
      - "9999999"
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "1000Mi"
        cpu: "500m"
  - name: gradle
    image: gradle
    imagePullPolicy: Always
    ttyEnabled: true
    command:
      - sleep
    args:
      - 99d
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "1000Mi"
        cpu: "500m"
