apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  volumes:
    - name: sharedvolume
      emptyDir: {}
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
  containers:
    - name: jnlp
      image: larribas/jenkins-jnlp-slave-with-ssh:1.0.0
      imagePullPolicy: Always
      args: "${computer.jnlpmac} ${computer.name}"
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"
    - name: docker
      image: docker
      imagePullPolicy: Always
      ttyEnabled: true
      command: 'cat'
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"
    - name: gradle
      image: gradle
      imagePullPolicy: Always
      ttyEnabled: true
      command: 'cat'
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"
