apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  volumes:
    - name: sharedvolume
      emptyDir: {}
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
  containers:
    - name: docker
      image: docker
      imagePullPolicy: Always
      tty: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"
    - name: gradle
      image: gradle
      imagePullPolicy: Always
      tty: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"